### ISSUE TITLE
Setup command-line tool and unit tests

### ISSUE THREAD

**Issue by gdemonet** [scality/changelog-binder#3]
Define the command-line tool skeleton (using Python and [Click](https://click.palletsprojects.com/en/7.x/)) and include unit testing (using `pytest`) and linting (using `pylint` and `mypy`). Also include packaging and minimal installation guide.

**Comment by NicolasT** [comment]
Not using `click`, but this is now done, I believe. If `click` is a requirement, can be re-opened...
